__pypi_packagename__ = "gogokit"
__version__ = "0.1.0"
# __token_url__ = "https://account.viagogo.com/oauth2/token"
# __root_url__ = "https://api.viagogo.net/v2"
__token_url__ = "https://test.www.viagogo.com/secure/oauth2/token"
__root_url__ = "https://qa.api.viagogo.net/v2"